# Generated by Django 4.0.4 on 2022-12-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatagoryWiseImage',
            new_name='CatagoryImage',
        ),
    ]
