# Generated by Django 4.0.4 on 2022-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('whatsapp_no', models.CharField(max_length=200)),
                ('makeup_catagory', models.CharField(max_length=200)),
                ('have_siders', models.BooleanField(default=False)),
                ('sider_count', models.IntegerField(default=False)),
                ('created_by', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=200)),
                ('paid_amount', models.CharField(max_length=200)),
                ('remaining_amount', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
